import '../../styles/globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { i18n } from '@/config/i18n.config';
import type { DefaultLayoutProps } from '@/types/pages.type';

const inter = Inter({ subsets: ['latin'] });

export async function generateStaticParams() {
  const languages = i18n.locales.map((locale) => ({ locale }));
  return languages;
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type Props = DefaultLayoutProps;

export default async function RootLayout({ children, params }: Props) {
  return (
    <html lang={params.locale}>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
